FROM golang:latest AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app ./cmd/tec-doc/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder ./app .

ENV TEC_DOC_POSTGRES_USERNAME csamuro
ENV TEC_DOC_POSTGRES_PASSWORD 1234
ENV TEC_DOC_POSTGRES_HOST db
ENV TEC_DOC_POSTGRES_PORT 5432
ENV TEC_DOC_POSTGRES_DB csamuro
ENV TEC_DOC_EXTERNAL_SERV_PORT 8001
ENV TEC_DOC_INTERNAL_SERV_PORT 8000
ENV TEC_DOC_LOG_LEVEL debug

EXPOSE 8000:8000
EXPOSE 8001:8001
CMD ["./app"]
