apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: suppliers-discounts-prices-go
  labels:
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: suppliers-discounts-prices-go
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30003

