# Enviroment (like as cluser name)
environment: prod-dl

replicaCount: 1

ports:
  - name: metrics
    containerPort: 8001
    protocol: TCP
  - name: api
    containerPort: 8000
    protocol: TCP

service:
  type: NodePort # Обязательный параметр для новых кластеров
  externalTrafficPolicy: Local # Обязательный параметр для новых кластеров
  ports:
    - port: 80
      name: api
      targetPort: 8000
