replicaCount: 1

resources:
  requests:
    memory: "500Mi"
    cpu: "0.5"
  limits:
    memory: "1000Mi"
    cpu: "1.0"

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent
  
# # Set imagePullSecrets if exist
imagePullSecrets:
 - name: harbor-registry-secret

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9090"

extendedLabels:
  department: "portal" 
  project: "tec-doc-api" 
  team: "seller-portal" 
  developer: "" 
  resources: "mongo" 
  dependencies: ""

readinessProbe:
  httpGet:
    path: "/readiness"
    port: 8001
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: "/health"
    port: 8001
  initialDelaySeconds: 5
  periodSeconds: 10

vault:
  enabled: true
  # entrypoint: ./app <- точка входа не задается т.к. совпадает с точкой входа по умолчанию
  role: vault-agent-injector-{{.Helm.Release.Environment}}  # vault injector role - выдается при интеграции службой технической поддержки
  authPath: auth/{{ .Helm.Release.Cluster }}.vault-auth-{{ .Helm.Release.Namespace }} # vault injector authPath - выдается при интеграции службой технической поддержки
  contents:
    - services/{{ .Helm.Release.Namespace }}/{{.Helm.Release.Environment}}/tec-doc:
        POSTGRES_USERNAME: POSTGRES_USERNAME
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
        TEC_DOC_CLIENT_API_KEY: TEC_DOC_CLIENT_API_KEY
        TEC_DOC_CLIENT_PROVIDER_ID: TEC_DOC_CLIENT_PROVIDER_ID

env:
  INTERNAL_SERV_PORT: ":8001"
  EXTERNAL_SERV_PORT: ":8000"
  LOG_LEVEL: "debug"
  POSTGRES_HOST: "5000"
  POSTGRES_PORT: "suppliers-discounts-prices-go-tecdoc-pgsql-haproxy.suppliers-discounts-prices-go.svc.k8s.dataline"
  POSTGRES_TIMEOUT: "30s"
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_MIN_CONNECTIONS: "10"
  CONTENT_CLIENT_URL: "http://source.content-card.svc.k8s.stage-dp/source/migration"
  CONTENT_CLIENT_TIMEOUT: "15s"
  TEC_DOC_CLIENT_URL: "https://webservice.tecalliance.services/pegasus-3-0/services/TecdocToCatDLB.jsonEndpoint?js"
  TEC_DOC_CLIENT_TIMEOUT: "15s"

