# https://git.wildberries.ru/devops/ci/templates/-/blob/master/README.md

.template_repo: &repo
  project: 'devops/ci/templates'
  ref: &ci_tmpl_vers 'release-v3.0.1'

variables:
  # hold pls
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers
  # ci vars
  GO_VER: "1.17"
  CI_TMPL_HELM_CHART_NAME: common-deploy
  CI_TMPL_HELM_CHART_VERSION: 2.1.0
  # list of services for build & deploy
  CI_TMPL_HELM_RELEASE_NAMES: "tec-doc-worker"
  CI_TMPL_HELM_RELEASE_NAMESPACE: suppliers-discounts-prices-go
  # list of clusters for deploy
  CI_TMPL_KUBE_CLUSTERS_DEV: "k8s.dldevel"
  CI_TMPL_KUBE_CLUSTERS_PROD: "k8s.datapro,k8s.dataline"

  # harbor project name
  REGISTRY_PROJECT: "portals"

  VAULT_JWT_AUTH: "jwt2"
  VAULT_JWT_ROLE_K8S_DLDEVEL: k8s_clusters-k8s.dldevel-$CI_TMPL_HELM_RELEASE_NAMESPACE
  VAULT_JWT_ROLE_K8S_DATALINE: k8s_clusters-k8s.dataline-$CI_TMPL_HELM_RELEASE_NAMESPACE
  VAULT_JWT_ROLE_K8S_DATAPRO: k8s_clusters-k8s.datapro-$CI_TMPL_HELM_RELEASE_NAMESPACE

include:
  - { <<: *repo, file: /pipelines/go.yml
