// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package content

import "github.com/satori/go.uuid"

type requestSuppliersGetOldSupplierID struct {
	SupplierID uuid.UUID `json:"supplierID"`
}

type responseSuppliersGetOldSupplierID struct {
	OldSupplierID int `json:"oldSupplierID"`
}
