// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package generated_client

type requestContentClientPushContent struct {
	Attributes []map[string]interface{} `json:"attributes"` // This field was defined with ellipsis (...).
}

// Formal exchange type, please do not delete.
type responseContentClientPushContent struct{}
