Enviroment (like as cluser name)
environment: dataline

replicaCount: 1

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8001"
  prometheus.io/scrape: "true"

ports:
  - name: metrics
    containerPort: 8001
    protocol: TCP
  - name: process
    containerPort: 8001
    protocol: TCP

readinessProbe:
  httpGet:
    path: "/readiness"
    port: 8001
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: "/health"
    port: 8001
  initialDelaySeconds: 5
  periodSeconds: 10

imagePullSecrets:
  - name: harbor-registry-secret

vault:
  enabled: true
  role: vault-agent-injector-prd
  authPath: auth/k8s.dataline.vault-auth-suppliers-discounts-prices-go
  contents:
    - services/suppliers-discounts-prices-go/prd/content-sync:
        MS_SQL_USERNAME: mssql_username
        MS_SQL_PASSWORD: mssql_password
        MS_SQL_DB_NAME: mssql_db_name
        NATS_SERVERS: nats_servers
        NATS_CLUSTER_ID: nats_cluster_id
        NATS_USER: nats_user
        NATS_PASSWORD: nats_password
        SUPPLIERS_ACCESS_KEY: suppliers_access_key
        PORTAL_NATS_SERVERS: portal_nats_servers
        PORTAL_NATS_CLUSTER_ID: portal_nats_cluster_id
        PORTAL_NATS_USER: portal_nats_user
        PORTAL_NATS_PASSWORD: portal_nats_password
        PRICES_CLIENT_ID: prices_client_id
        PRICES_PASSWORD: prices_password
        FULL_NATS_SERVERS: full_nats_servers
        FULL_NATS_CLUSTER_ID: full_nats_cluster_id
        FULL_NATS_USER: full_nats_user
        FULL_NATS_PASSWORD: full_nats_password

env:
  LOG_LEVEL: "debug"
  INTERNAL_SERV_PORT: "8000"
  EXTERNAL_SERV_PORT: "8001"
  LISTEN_INTERNAL: ""
  POSTGRES_USERNAME: "csamuro"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "csamuro"
  POSTGRES_TIMEOUT: "30s"
  MAX_CONNECTIONS: "100"
  MIN_CONNECTIONS: "10"
service:
  enabled: true
  ports:
    - port: 80
      name: process
      targetPort: 8001

resources:
  requests:
    memory: "500Mi"
    cpu: "0.5"
  limits:
    memory: "3024Mi"
    cpu: "2.0"
