basePath: /api/v1/
definitions:
  errinfo.errInf:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  model.Article:
    properties:
      articleCriteria:
        items:
          $ref: '#/definitions/model.ArticleCriteria'
        type: array
      articleNumber:
        type: string
      crossNumbers:
        items:
          $ref: '#/definitions/model.CrossNumbers'
        type: array
      genericArticleDescription:
        type: string
      images:
        items:
          type: string
        type: array
      linkageTargets:
        items:
          $ref: '#/definitions/model.LinkageTargets'
        type: array
      mfrName:
        type: string
      oemNumbers:
        items:
          $ref: '#/definitions/model.OEM'
        type: array
      packageArticleCriteria:
        items:
          $ref: '#/definitions/model.ArticleCriteria'
        type: array
    type: object
  model.ArticleCriteria:
    properties:
      criteriaAbbrDescription:
        type: string
      criteriaDescription:
        type: string
      criteriaType:
        type: string
      criteriaUnitDescription:
        type: string
      formattedValue:
        type: string
      rawValue:
        type: string
    type: object
  model.CrossNumbers:
    properties:
      articleNumber:
        type: string
      mfrName:
        type: string
    type: object
  model.GetTecDocArticlesRequest:
    properties:
      articleNumber:
        type: string
      brand:
        type: string
    type: object
  model.LinkageTargets:
    properties:
      beginYearMonth:
        type: string
      endYearMonth:
        type: string
      linkageTargetId:
        type: integer
      mfrName:
        type: string
      vehicleModelSeriesName:
        type: string
    type: object
  model.OEM:
    properties:
      articleNumber:
        type: string
      mfrName:
        type: string
    type: object
  model.Product:
    properties:
      article:
        type: string
      articleSupplier:
        type: string
      barcode:
        type: string
      brand:
        type: string
      errorResponse:
        type: string
      id:
        type: integer
      price:
        type: integer
      status:
        type: integer
      subject:
        type: string
      updateDate:
        type: string
      uploadDate:
        type: string
      uploadId:
        type: integer
    type: object
  model.Task:
    properties:
      id:
        type: integer
      ip:
        type: string
      productsFailed:
        type: integer
      productsProcessed:
        type: integer
      productsTotal:
        type: integer
      status:
        type: integer
      supplierID:
        type: integer
      updateDate:
        type: string
      uploadDate:
        type: string
      userID:
        type: integer
    type: object
  model.UploadIdRequest:
    properties:
      uploadID:
        example: 1
        type: integer
    type: object
host: localhost:8002
info:
  contact: {}
  title: Tec-Doc API
  version: "1.0"
paths:
  /articles/enrichment:
    post:
      description: get task list
      operationId: articles_enrichment
      parameters:
      - description: brand && article - about product
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.GetTecDocArticlesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/model.Article'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetTecDocArticles
      tags:
      - product
  /excel:
    get:
      description: download excel table template
      operationId: excel_template
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: ExcelTemplate
      tags:
      - excel
    post:
      description: upload excel table containing products info
      operationId: load_from_excel
      parameters:
      - description: binary excel file
        in: body
        name: excel_file
        required: true
        schema:
          items:
            type: integer
          type: array
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: LoadFromExcel
      tags:
      - excel
  /excel/enrichment:
    post:
      description: Enrichment excel file, limit entiies in file = 10000
      operationId: enrich_excel
      parameters:
      - description: binary excel file
        in: body
        name: excel_file
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: ProductsEnrichedExcel
      tags:
      - excel
  /product_history:
    post:
      consumes:
      - application/json
      description: get product list
      operationId: products_history
      parameters:
      - description: limit of contents
        in: query
        name: limit
        required: true
        type: string
      - description: offset of contents
        in: query
        name: offset
        required: true
        type: string
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      - description: The input body.<br /> UploadID is ID of previously uploaded task.
        in: body
        name: InputBody
        required: true
        schema:
          $ref: '#/definitions/model.UploadIdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetProductsHistory
      tags:
      - product
  /task_history:
    get:
      description: get task list
      operationId: supplier_task_history
      parameters:
      - description: limit of contents
        in: query
        name: limit
        required: true
        type: string
      - description: offset of contents
        in: query
        name: offset
        required: true
        type: string
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetSupplierTaskHistory
      tags:
      - product
schemes:
- http
swagger: "2.0"
