basePath: /
definitions:
  errinfo.errInf:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  model.Article:
    properties:
      articleNumber:
        type: string
      brand:
        type: string
      country:
        type: string
      ean:
        items:
          type: string
        type: array
      oemnumbers:
        items:
          type: string
        type: array
      packageHeight:
        $ref: '#/definitions/model.ArticleCriteria'
      packageLength:
        $ref: '#/definitions/model.ArticleCriteria'
      packageWidth:
        $ref: '#/definitions/model.ArticleCriteria'
      panoramicImages:
        items:
          $ref: '#/definitions/model.Image'
        type: array
      pictures:
        items:
          $ref: '#/definitions/model.Image'
        type: array
      productGroups:
        items:
          type: string
        type: array
      relatedVehicles:
        items:
          type: string
        type: array
      replacedByArticles:
        items:
          type: string
        type: array
      weight:
        $ref: '#/definitions/model.ArticleCriteria'
    type: object
  model.ArticleCriteria:
    properties:
      criteriaAbbrDescription:
        type: string
      criteriaDescription:
        type: string
      criteriaId:
        type: integer
      criteriaType:
        type: string
      criteriaUnitDescription:
        type: string
      formattedValue:
        type: string
      immediateDisplay:
        type: boolean
      isInterval:
        type: boolean
      isMandatory:
        type: boolean
      rawValue:
        type: string
    type: object
  model.GetProductsHistoryRequest:
    properties:
      UploadID:
        example: 1
        type: integer
    type: object
  model.GetTecDocArticlesRequest:
    properties:
      ArticleNumber:
        example: "0451103274"
        type: string
      Brand:
        example: BOSCH
        type: string
    type: object
  model.Image:
    properties:
      fileName:
        type: string
      headerDescription:
        type: string
      headerKey:
        type: integer
      imageURL50:
        type: string
      imageURL100:
        type: string
      imageURL200:
        type: string
      imageURL400:
        type: string
      imageURL800:
        type: string
      imageURL1600:
        type: string
      imageURL3200:
        type: string
      typeDescription:
        type: string
      typeKey:
        type: integer
    type: object
  model.Product:
    properties:
      article:
        type: string
      brand:
        type: string
      cardNumber:
        type: integer
      category:
        type: string
      errorResponse:
        type: string
      id:
        type: integer
      manufacturerArticle:
        type: string
      price:
        type: integer
      providerArticle:
        type: string
      sku:
        type: string
      status:
        type: integer
      updateDate:
        type: string
      uploadDate:
        type: string
      uploadId:
        type: integer
    type: object
  model.Task:
    properties:
      id:
        type: integer
      ip:
        type: string
      productsFailed:
        type: integer
      productsProcessed:
        type: integer
      productsTotal:
        type: integer
      status:
        type: integer
      supplierID:
        type: integer
      updateDate:
        type: string
      uploadDate:
        type: string
      userID:
        type: integer
    type: object
host: localhost:8002
info:
  contact: {}
  title: Tec-Doc API
  version: "1.0"
paths:
  /excel_template:
    get:
      description: download excel table template
      operationId: excel_template
      parameters:
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      produces:
      - application/vnd.ms-excel
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: ExcelTemplate
      tags:
      - excel
  /load_from_excel:
    post:
      description: upload excel table containing products info
      operationId: load_from_excel
      parameters:
      - description: excel file
        in: formData
        name: excel_file
        required: true
        type: file
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: LoadFromExcel
      tags:
      - excel
  /product_history:
    post:
      consumes:
      - application/json
      description: get product list
      operationId: products_history
      parameters:
      - description: limit of contents
        in: query
        name: limit
        required: true
        type: string
      - description: offset of contents
        in: query
        name: offset
        required: true
        type: string
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      - description: The input body.<br /> UploadID is ID of uploaded task.
        in: body
        name: InputBody
        required: true
        schema:
          $ref: '#/definitions/model.GetProductsHistoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetProductsHistory
      tags:
      - product
  /task_history:
    get:
      description: get task list
      operationId: supplier_task_history
      parameters:
      - description: limit of contents
        in: query
        name: limit
        required: true
        type: string
      - description: offset of contents
        in: query
        name: offset
        required: true
        type: string
      - description: ID of user
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: ID of supplier
        in: header
        name: X-Supplier-Id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetSupplierTaskHistory
      tags:
      - product
  /tecdoc_articles:
    post:
      description: get tecdoc articles
      operationId: tecdoc_articles
      parameters:
      - description: The input body.<br />Brand is brand name, ArticleNumber is article
          of product.
        in: body
        name: InputBody
        required: true
        schema:
          $ref: '#/definitions/model.GetTecDocArticlesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errinfo.errInf'
      summary: GetTecDocArticles
      tags:
      - tecdoc
swagger: "2.0"
