// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package suppliers

type requestSourceMigration struct {
	Attributes []map[string]interface{} `json:"attributes"` // This field was defined with ellipsis (...).
}

// Formal exchange type, please do not delete.
type responseSourceMigration struct{}
